{{- if and (not .Values.github.existingSecret) .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odigos-ai-agent.githubSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odigos-ai-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.existingSecretKey }}: {{ .Values.github.token | quote }}
{{- end }}
