apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "odigos-ai-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odigos-ai-agent.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ .name }}
{{- end }}
{{- end }}
